#pragma once

#define DEVICE_NAME "Intelligent-Rover-Main"

#define SERIAL_BAUD_RATE 115200

#define MOTOR_PWM_FREQ 20000
#define MOTOR_PWM_RESOLUTION 8

#define DEFAULT_MOTOR_SPEED 180
#define MAX_MOTOR_SPEED 255
#define MIN_MOTOR_SPEED 0

#define WATCHDOG_TIMEOUT_SECONDS 8

#define SENSOR_READ_INTERVAL_MS 2000
#define GPS_READ_INTERVAL_MS 1000
#define THINGSPEAK_UPLOAD_INTERVAL_MS 15000
#define SYSTEM_HEALTH_INTERVAL_MS 5000