[platformio]
default_envs = esp32-main

[env:esp32-main]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

monitor_filters =
    esp32_exception_decoder

board_build.flash_mode = dio
board_build.partitions = huge_app.csv

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D ENABLE_BLUETOOTH_CLASSIC
    -D ENABLE_OTA
    -D ENABLE_THINGSPEAK
    -I include
    -I include/config
    -I include/pins
    -I lib/TelemetryManager

lib_deps =
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
    mikalhart/TinyGPSPlus
    bblanchon/ArduinoJson

upload_protocol = esptool